# Generated by Django 5.2.4 on 2025-07-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='paht',
            new_name='path',
        ),
    ]
